name: "Code-Style Check"

on: [ push, pull_request ]

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v5

            -   name: Checking PHP Syntax
                uses: TheDragonCode/codestyler@v5
